// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dummy.sql

package repository

import (
	"context"
)

const getDummyTime = `-- name: GetDummyTime :one
SELECT NOW() as current_time
`

func (q *Queries) GetDummyTime(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getDummyTime)
	var current_time interface{}
	err := row.Scan(&current_time)
	return current_time, err
}
