// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Member struct {
	ID             uuid.UUID             `json:"id"`
	UserID         uuid.UUID             `json:"user_id"`
	Code           string                `json:"code"`
	Slug           string                `json:"slug"`
	FirstName      string                `json:"first_name"`
	LastName       string                `json:"last_name"`
	Phone          string                `json:"phone"`
	Address        sql.NullString        `json:"address"`
	NextOfKinName  sql.NullString        `json:"next_of_kin_name"`
	NextOfKinPhone sql.NullString        `json:"next_of_kin_phone"`
	MembershipData pqtype.NullRawMessage `json:"membership_data"`
	CreatedAt      time.Time             `json:"created_at"`
	UpdatedAt      sql.NullTime          `json:"updated_at"`
	DeletedAt      sql.NullTime          `json:"deleted_at"`
}

type Role struct {
	ID          uuid.UUID      `json:"id"`
	Permission  string         `json:"permission"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Token struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Token     string       `json:"token"`
	IsValid   bool         `json:"is_valid"`
	TokenType string       `json:"token_type"`
	ExpiresAt time.Time    `json:"expires_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type User struct {
	ID               uuid.UUID      `json:"id"`
	Email            string         `json:"email"`
	PasswordHash     sql.NullString `json:"password_hash"`
	EmailConfirmedAt sql.NullTime   `json:"email_confirmed_at"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
}

type UserRole struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	RoleID    uuid.UUID `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
}
