// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Role struct {
	ID          uuid.UUID      `json:"id"`
	Permission  string         `json:"permission"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type User struct {
	ID               uuid.UUID      `json:"id"`
	Email            string         `json:"email"`
	FirstName        string         `json:"first_name"`
	LastName         string         `json:"last_name"`
	Phone            string         `json:"phone"`
	Address          sql.NullString `json:"address"`
	EmailConfirmedAt sql.NullTime   `json:"email_confirmed_at"`
	PasswordHash     sql.NullString `json:"password_hash"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	CreatedAt        time.Time      `json:"created_at"`
}

type UserRole struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	RoleID    uuid.UUID `json:"role_id"`
	CreatedAt time.Time `json:"created_at"`
}
