// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package repository

import (
	"context"
)

const dummyQuery = `-- name: DummyQuery :one
SELECT 1
`

// This is a placeholder file for sqlc to run.
func (q *Queries) DummyQuery(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, dummyQuery)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
